### ISSUE TITLE
BugFix for ContextDatastore

### ISSUE THREAD

**Issue by MagicShel** [chatrpg-cs/chatrpg-be#43]
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.NullPointerException: messageEventData not set
Caused by: java.lang.NullPointerException: messageEventData not set
	at es.thalesalv.gptbot.adapters.data.ContextDatastore.lambda$1(ContextDatastore.java:36)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at es.thalesalv.gptbot.adapters.data.ContextDatastore.getMessageEventData(ContextDatastore.java:36)
	at es.thalesalv.gptbot.application.service.ChatGptModelService.generate(ChatGptModelService.java:37)
```

**Comment by thaalesalves** [comment]
Like we discussed, we can pass that as method parameters to avoid using the thread context, since we're going reactive and that's throwing problems. We can use this as a temporary solution until we refactor the persona system. Then this thread context won't even be necessary anymore. I'll implement the fix and we can expand on the idea of this persona system so this is fixed once and for all.
